# Generated by Django 2.2.13 on 2020-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('capacity', models.PositiveSmallIntegerField(help_text='number of seats', verbose_name='capacity')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ('name',),
            },
        ),
    ]
