# Generated by Django 2.2.13 on 2020-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end',
            field=models.DateTimeField(editable=False, verbose_name='ends at'),
        ),
    ]
