# Generated by Django 2.2.13 on 2020-06-19 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('paid_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='paid amount')),
                ('seats', models.SmallIntegerField(blank=True, default=1, verbose_name='seats')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Showtime', verbose_name='showtime')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ('created',),
            },
        ),
    ]
