# Generated by Django 2.2.13 on 2020-06-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='seats'),
        ),
    ]
